package org.wumeng.jframe.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePosts<M extends BasePosts<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPublisher(java.lang.Integer publisher) {
		set("publisher", publisher);
		return (M)this;
	}
	
	public java.lang.Integer getPublisher() {
		return getInt("publisher");
	}

	public M setPublishTime(java.lang.Long publishTime) {
		set("publish_time", publishTime);
		return (M)this;
	}
	
	public java.lang.Long getPublishTime() {
		return getLong("publish_time");
	}

	public M setLastModifyTime(java.lang.Long lastModifyTime) {
		set("last_modify_time", lastModifyTime);
		return (M)this;
	}
	
	public java.lang.Long getLastModifyTime() {
		return getLong("last_modify_time");
	}

}
