package org.wumeng.jframe.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.wumeng.jframe.model.base.BasePosts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Posts extends BasePosts<Posts> {

    public static final Posts dao = new Posts().dao();

    /**
     * 发布时间
     */
    @JSONField(name = "publish_time")
    private String publishTime;
    /**
     * 最后修改时间
     */
    @JSONField(name = "last_modify_time")
    private String lastModifyTime;
}
