package org.wumeng.jframe.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.wumeng.jframe.model.base.BaseUser;

/**
 * 用户模型
 * 驼峰风格和下划线风格转换，无需转换的字段可以无需增加，直接根据数据库字段生成
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User().dao();

    /**
     * 用户名
     */
    @JSONField(name = "user_name")
    private String userName;
    /**
     * 昵称
     */
    @JSONField(name = "nick_name")
    private String nickName;
    /**
     * 登录密码
     */
    @JSONField(name = "pass_word")
    private String passWord;

}
